/** Manifest-driven financial video templates with finite transitions and safe captions. */
import React from 'react';
import {AbsoluteFill, Audio, Img, interpolate, OffthreadVideo, Sequence, spring, staticFile, useCurrentFrame, useVideoConfig} from 'remotion';

type SceneSpec={id:string;purpose:string;title?:string;duration_seconds:number;transition?:'cut'|'fade'|'slide'|'wipe'|'zoom';chart?:string};
type CaptionConfig={enabled:boolean;max_lines:number;safe_zone:{top:number;bottom:number;left:number;right:number}};
export type Manifest={output:{width:number;height:number;fps:number};brand?:{primary_color:string;font_family:string};scenes:SceneSpec[];narration:{segments:Array<{scene_id:string;display_text:string}>};audio?:{src?:string|null};charts:{charts:Array<any>};timeline:{total_frames:number;events:Array<any>};assets?:{scenes:Array<any>};captions?:CaptionConfig;disclaimer:string};

/** Animated bar chart driven entirely by a validated chart specification. */
const Bars:React.FC<{chart:any;color:string}>=({chart,color})=>{const f=useCurrentFrame();const values=(chart.values??[]).map(Number);const max=Math.max(...values,1);return <div style={{display:'flex',alignItems:'end',gap:70,height:480}}>{values.map((v:number,i:number)=><div key={`${v}-${i}`} style={{textAlign:'center',fontSize:30}}><div style={{height:interpolate(f-i*8,[0,35],[0,(v/max)*390],{extrapolateRight:'clamp'}),width:150,background:color,borderRadius:'16px 16px 0 0'}}/><b>{v.toLocaleString()}</b><div>{chart.labels?.[i]??''}</div></div>)}</div>};

/** True animated donut chart for business-mix scenarios. */
const Donut:React.FC<{chart:any;color:string}>=({chart,color})=>{const f=useCurrentFrame();const values=(chart.values??[1]).map(Number);const total=values.reduce((a:number,b:number)=>a+b,0)||1;const target=values[0]/total*100;const p=interpolate(f,[0,45],[0,target],{extrapolateRight:'clamp'});return <div style={{display:'flex',gap:90,alignItems:'center'}}><div style={{width:350,height:350,borderRadius:'50%',background:`conic-gradient(${color} ${p}%,#dce5d7 0)`,display:'grid',placeItems:'center'}}><div style={{width:210,height:210,borderRadius:'50%',background:'#fff',display:'grid',placeItems:'center',fontSize:65,fontWeight:900,color}}>{p.toFixed(0)}%</div></div><div style={{fontSize:42}}>{chart.labels?.[0]??'Primary segment'}</div></div>};

/** Guidance or option-level range with animated low/mid/high markers. */
const Guidance:React.FC<{chart:any;color:string}>=({chart,color})=>{const f=useCurrentFrame();const x=interpolate(f,[0,45],[0,1],{extrapolateRight:'clamp'});return <div style={{width:1050}}><div style={{fontSize:54}}>{chart.title??'Guidance range'}</div><div style={{height:22,background:'#dfe8d8',marginTop:80,position:'relative'}}><div style={{position:'absolute',left:`${20*(1-x)}%`,right:`${20*(1-x)}%`,height:22,background:color}}/><div style={{position:'absolute',left:'50%',top:-55,fontSize:40,fontWeight:800}}>{chart.midpoint??''}</div></div><div style={{display:'flex',justifyContent:'space-between',fontSize:32,marginTop:30}}><span>{chart.low??''}</span><span>{chart.high??''}</span></div></div>};

/** Movable price line with template-bound call, strike, and kick-in levels. */
const PriceLine:React.FC<{chart:any;color:string}>=({chart,color})=>{const f=useCurrentFrame();const values=(chart.values??[]).map(Number);const max=Math.max(...values,1),min=Math.min(...values,0),span=Math.max(1,max-min);const points=values.map((v:number,i:number)=>`${i*900/Math.max(1,values.length-1)},${360-(v-min)*320/span}`);const reveal=interpolate(f,[0,60],[0,1],{extrapolateRight:'clamp'});return <svg width="1000" height="480" viewBox="0 0 1000 480"><polyline points={points.join(' ')} fill="none" stroke={color} strokeWidth="12" pathLength="1" strokeDasharray="1" strokeDashoffset={1-reveal}/>{(chart.key_levels??[]).map((level:any,i:number)=>{const y=360-(Number(level.value)-min)*320/span;return <g key={i}><line x1="0" x2="920" y1={y} y2={y} stroke="#ffb703" strokeWidth="4" strokeDasharray="12 10"/><text x="930" y={y+10} fill="currentColor" fontSize="28">{level.kind}: {level.value}</text></g>})}</svg>};

/** Select one of the finite renderer templates; schema validation rejects unknown types. */
const Chart:React.FC<{chart:any;color:string}>=({chart,color})=>chart.type==='bar'?<Bars chart={chart} color={color}/>:chart.type==='donut'?<Donut chart={chart} color={color}/>:chart.type==='range'?<Guidance chart={chart} color={color}/>:<PriceLine chart={chart} color={color}/>;

/** Split long subtitles into timed chunks and enforce the configured safe rectangle. */
const Caption:React.FC<{text:string;config?:CaptionConfig}>=({text,config})=>{const f=useCurrentFrame();const {durationInFrames}=useVideoConfig();if(config?.enabled===false||!text)return null;const maxLines=config?.max_lines??2;const chunkSize=Math.max(16,maxLines*22);const chunks=text.match(new RegExp(`.{1,${chunkSize}}`,'g'))??[''];const index=Math.min(chunks.length-1,Math.floor(f/Math.max(1,durationInFrames/chunks.length)));const safe=config?.safe_zone;return <div style={{position:'absolute',left:safe?.left??96,right:safe?undefined:96,width:safe?Math.max(100,safe.right-safe.left):undefined,top:safe?.top,bottom:safe?undefined:80,maxHeight:safe?Math.max(80,safe.bottom-safe.top):undefined,overflow:'hidden',background:'rgba(0,0,0,.82)',color:'white',borderRadius:16,padding:'20px 34px',fontSize:37,lineHeight:1.4,textAlign:'center',boxSizing:'border-box',display:'grid',placeItems:'center'}}>{chunks[index]}</div>};

/** Apply only the renderer-supported transition selected in the scene plan. */
const transitionStyle=(template:SceneSpec['transition'],progress:number):React.CSSProperties=>template==='fade'?{opacity:progress}:template==='slide'?{transform:`translateX(${(1-progress)*120}px)`,opacity:progress}:template==='wipe'?{clipPath:`inset(0 ${100*(1-progress)}% 0 0)`}:template==='zoom'?{transform:`scale(${.88+.12*progress})`,opacity:progress}:{opacity:1};

/** Render one scene while keeping chart/media content above the caption region. */
const Scene:React.FC<{scene:SceneSpec;text:string;index:number;manifest:Manifest;chart:any;asset:any}>=({scene,text,index,manifest,chart,asset})=>{const f=useCurrentFrame();const {fps}=useVideoConfig();const enter=scene.transition==='cut'?1:spring({frame:f,fps,config:{damping:20}});const color=manifest.brand?.primary_color??'#76B900';const ink='#0d160d';const isDisclaimer=/disclaimer/i.test(scene.purpose);const success=asset?.attempts?.find((x:any)=>x.status==='succeeded'&&x.result);const mediaUrl=success?.result?.video_url??success?.result?.image_urls?.[0]??success?.result?.url??success?.result?.artifact_url;const isVideo=asset?.strategy==='bach_text_to_video'||asset?.strategy==='bach_elements_to_video';const media=mediaUrl?(isVideo?<OffthreadVideo src={mediaUrl} muted style={{width:'100%',height:'100%',objectFit:'cover'}}/>:<Img src={mediaUrl} style={{width:'80%',height:'80%',objectFit:'contain',transform:`scale(${1+.06*enter})`}}/>):null;return <AbsoluteFill style={{background:index%2?'#f3f7ef':'#111b10',color:index%2?ink:'white',fontFamily:`${manifest.brand?.font_family??'Inter'}, PingFang SC, sans-serif`,padding:'70px 90px 25%',...transitionStyle(scene.transition,enter)}}><div style={{fontSize:30,color,fontWeight:800}}>FINANCIAL VIDEO</div><h1 style={{fontSize:70,maxWidth:1500}}>{scene.title??scene.purpose}</h1><div style={{flex:1,display:'grid',placeItems:'center'}}>{isDisclaimer?<div style={{fontSize:42,lineHeight:1.6,textAlign:'center',maxWidth:1400}}>{manifest.disclaimer}</div>:chart?<Chart chart={chart} color={color}/>:media??<div style={{fontSize:220}}>📊✨</div>}</div><Caption text={text} config={manifest.captions}/></AbsoluteFill>};

/** Map approved manifest scenes to deterministic frame ranges and templates. */
export const FinancialVideo:React.FC<Manifest>=(props)=>{let from=0;return <AbsoluteFill>{props.audio?.src?<Audio src={staticFile(props.audio.src)}/>:null}{props.scenes.map((scene,index)=>{const duration=Math.round(scene.duration_seconds*props.output.fps);const text=props.narration.segments.find(x=>x.scene_id===scene.id)?.display_text??'';const chart=props.charts.charts.find((x:any)=>x.id===scene.chart);const asset=props.assets?.scenes.find((x:any)=>x.scene_id===scene.id);const node=<Sequence key={scene.id} from={from} durationInFrames={duration}><Scene scene={scene} text={text} index={index} manifest={props} chart={chart} asset={asset}/></Sequence>;from+=duration;return node})}</AbsoluteFill>};
