/** Deterministic financial video composition with template-bound motion and safe captions. */
import React from 'react';
import {AbsoluteFill, Audio, Img, interpolate, OffthreadVideo, Sequence, spring, staticFile, useCurrentFrame, useVideoConfig} from 'remotion';

export type Manifest={output:{width:number;height:number;fps:number};scenes:Array<{id:string;purpose:string;duration_seconds:number}>;narration:{segments:Array<{scene_id:string;display_text:string}>};audio?:{src?:string|null};charts:{charts:Array<any>};timeline:{total_frames:number;events:Array<any>};assets?:{scenes:Array<any>};disclaimer:string};
const green='#76B900', ink='#0d160d';

/** Animated bar chart driven entirely by a manifest chart specification. */
const Bars:React.FC<{chart:any}>=({chart})=>{const f=useCurrentFrame();const values=(chart?.values??[]).map(Number);const max=Math.max(...values,1);return <div style={{display:'flex',alignItems:'end',gap:70,height:480}}>{values.map((v:number,i:number)=><div key={`${v}-${i}`} style={{textAlign:'center',fontSize:30}}><div style={{height:interpolate(f-i*8,[0,35],[0,(v/max)*390],{extrapolateRight:'clamp'}),width:150,background:green,borderRadius:'16px 16px 0 0'}}/><b>{v.toLocaleString()}</b><div>{chart.labels?.[i]??''}</div></div>)}</div>};

/** Data-center mix visual that reuses the locked chip mascot concept. */
const Mix:React.FC<{chart:any}>=({chart})=>{const f=useCurrentFrame();const values=(chart?.values??[1]).map(Number);const total=values.reduce((a:number,b:number)=>a+b,0)||1;const target=values[0]/total*100;const p=interpolate(f,[0,45],[0,target],{extrapolateRight:'clamp'});return <div style={{display:'flex',gap:90,alignItems:'center'}}><div style={{fontSize:190}}>🤖</div><div><div style={{fontSize:130,fontWeight:900,color:green}}>{p.toFixed(0)}%</div><div style={{fontSize:42}}>{chart?.labels?.[0]??'Primary segment'}</div></div></div>};

/** Guidance range and midpoint animation with explicit key levels. */
const Guidance:React.FC<{chart:any}>=({chart})=>{const f=useCurrentFrame();const x=interpolate(f,[0,45],[0,1],{extrapolateRight:'clamp'});return <div style={{width:1050}}><div style={{fontSize:54}}>{chart?.title??'Guidance range'}</div><div style={{height:22,background:'#dfe8d8',marginTop:80,position:'relative'}}><div style={{position:'absolute',left:`${20*x}%`,right:`${20*x}%`,height:22,background:green}}/><div style={{position:'absolute',left:'50%',top:-55,fontSize:40,fontWeight:800}}>{chart?.midpoint??''}</div></div><div style={{display:'flex',justifyContent:'space-between',fontSize:32,marginTop:30}}><span>{chart?.low??''}</span><span>{chart?.high??''}</span></div></div>};

/** Select one of the finite renderer templates; unknown types degrade to a text card. */
const Chart:React.FC<{chart:any}>=({chart})=>chart?.type==='bar'?<Bars chart={chart}/>:chart?.type==='donut'?<Mix chart={chart}/>:chart?.type==='range'?<Guidance chart={chart}/>:<div style={{fontSize:54,textAlign:'center'}}>{chart?.title??'Financial overview'}</div>;

/** One scene renderer; layout always reserves the lower caption safe area. */
const Scene:React.FC<{scene:any;text:string;index:number;disclaimer:string;chart:any;asset:any}>=({scene,text,index,disclaimer,chart,asset})=>{const f=useCurrentFrame();const {fps}=useVideoConfig();const enter=spring({frame:f,fps,config:{damping:18}});const isDisclaimer=/disclaimer/i.test(scene.purpose??'');const success=asset?.attempts?.find((x:any)=>x.status==='succeeded'&&x.result);const mediaUrl=success?.result?.url??success?.result?.artifact_url;const media=mediaUrl?(asset.strategy==='bach_video'?<OffthreadVideo src={mediaUrl} muted style={{width:'100%',height:'100%',objectFit:'cover'}}/>:<Img src={mediaUrl} style={{width:'80%',height:'80%',objectFit:'contain',transform:`scale(${1+.06*enter})`}}/>):null;return <AbsoluteFill style={{background:index%2?'#f3f7ef':'#111b10',color:index%2?ink:'white',fontFamily:'Inter, PingFang SC, sans-serif',padding:'90px 110px 250px',transform:`scale(${.96+.04*enter})`,opacity:enter}}><div style={{fontSize:30,color:green,fontWeight:800}}>FINANCIAL VIDEO</div><h1 style={{fontSize:70,maxWidth:1500}}>{scene.title??scene.purpose??'Financial overview'}</h1><div style={{flex:1,display:'grid',placeItems:'center'}}>{isDisclaimer?<div style={{fontSize:42,lineHeight:1.6,textAlign:'center',maxWidth:1400}}>{disclaimer}</div>:chart?<Chart chart={chart}/>:media??<div style={{fontSize:220}}>📊✨</div>}</div><div style={{position:'absolute',left:96,right:96,bottom:80,minHeight:110,background:'rgba(0,0,0,.82)',color:'white',borderRadius:16,padding:'22px 38px',fontSize:37,lineHeight:1.45,textAlign:'center'}}>{text}</div></AbsoluteFill>};

/** Full composition maps manifest scenes to deterministic frame ranges. */
export const FinancialVideo:React.FC<Manifest>=(props)=>{let from=0;return <AbsoluteFill>{props.audio?.src?<Audio src={staticFile(props.audio.src)}/>:null}{props.scenes.map((s,i)=>{const duration=Math.round(s.duration_seconds*props.output.fps);const text=props.narration.segments.find(x=>x.scene_id===s.id)?.display_text??'';const chart=props.charts.charts.find((x:any)=>x.id===(s as any).chart);const asset=props.assets?.scenes.find((x:any)=>x.scene_id===s.id);const node=<Sequence key={s.id} from={from} durationInFrames={duration}><Scene scene={s} text={text} index={i} disclaimer={props.disclaimer} chart={chart} asset={asset}/></Sequence>;from+=duration;return node})}</AbsoluteFill>};
