/** Manifest-driven financial video templates with finite transitions and safe captions. */
import React from 'react';
import {AbsoluteFill, Audio, Img, interpolate, Loop, OffthreadVideo, Sequence, spring, staticFile, useCurrentFrame, useVideoConfig} from 'remotion';

type SceneSpec={id:string;kind?:'content'|'disclaimer';visual_kind?:'chart'|'metric_cards'|'broll'|'disclaimer';purpose:string;title?:string;duration_seconds:number;transition?:'cut'|'fade'|'slide'|'wipe'|'zoom';chart?:string};
type CaptionConfig={enabled:boolean;max_lines:number;safe_zone:{top:number;bottom:number;left:number;right:number}};
type CaptionCue={scene_id:string;text:string;start_seconds:number;end_seconds:number;from_frame:number;to_frame:number};
export type Manifest={output:{width:number;height:number;fps:number};brand?:{primary_color:string;font_family:string};scenes:SceneSpec[];narration:{segments:Array<{scene_id:string;display_text:string}>};audio?:{src?:string|null};charts:{charts:Array<any>};timeline:{total_frames:number;events:Array<any>;caption_cues?:CaptionCue[]};caption_cues?:CaptionCue[];assets?:{scenes:Array<any>};captions?:CaptionConfig;disclaimer:string};

/** Animated bar chart driven entirely by a validated chart specification. */
const Bars:React.FC<{chart:any;color:string}>=({chart,color})=>{const f=useCurrentFrame();const values=(chart.values??[]).map(Number);const max=Math.max(...values,1);return <div style={{display:'flex',alignItems:'end',gap:70,height:480}}>{values.map((v:number,i:number)=><div key={`${v}-${i}`} style={{textAlign:'center',fontSize:30}}><div style={{height:interpolate(f-i*8,[0,35],[0,(v/max)*390],{extrapolateRight:'clamp'}),width:150,background:color,borderRadius:'16px 16px 0 0'}}/><b>{v.toLocaleString()}</b><div>{chart.labels?.[i]??''}</div></div>)}</div>};

/** Horizontal bars keep long financial labels legible. */
const HorizontalBars:React.FC<{chart:any;color:string}>=({chart,color})=>{const f=useCurrentFrame();const values=(chart.values??[]).map(Number);const max=Math.max(...values.map(Math.abs),1);return <div style={{width:1100,display:'grid',gap:22}}>{values.map((value:number,index:number)=><div key={index} style={{display:'grid',gridTemplateColumns:'260px 1fr 160px',gap:22,alignItems:'center',fontSize:27}}><span style={{textAlign:'right'}}>{chart.labels?.[index]??''}</span><div style={{height:34,background:'#dce5d7',borderRadius:17,overflow:'hidden'}}><div style={{height:'100%',width:`${interpolate(f-index*5,[0,32],[0,Math.abs(value)/max*100],{extrapolateLeft:'clamp',extrapolateRight:'clamp'})}%`,background:color,borderRadius:17}}/></div><b>{chart.formatted_values?.[index]??value.toLocaleString()}</b></div>)}</div>};

/** True animated donut chart for business-mix scenarios. */
const Donut:React.FC<{chart:any;color:string}>=({chart,color})=>{const f=useCurrentFrame();const values=(chart.values??[1]).map(Number);const total=values.reduce((a:number,b:number)=>a+b,0)||1;const target=values[0]/total*100;const p=interpolate(f,[0,45],[0,target],{extrapolateRight:'clamp'});return <div style={{display:'flex',gap:90,alignItems:'center'}}><div style={{width:350,height:350,borderRadius:'50%',background:`conic-gradient(${color} ${p}%,#dce5d7 0)`,display:'grid',placeItems:'center'}}><div style={{width:210,height:210,borderRadius:'50%',background:'#fff',display:'grid',placeItems:'center',fontSize:65,fontWeight:900,color}}>{p.toFixed(0)}%</div></div><div style={{fontSize:42}}>{chart.labels?.[0]??'Primary segment'}</div></div>};

/** Guidance or option-level range with animated low/mid/high markers. */
const Guidance:React.FC<{chart:any;color:string}>=({chart,color})=>{const f=useCurrentFrame();const x=interpolate(f,[0,45],[0,1],{extrapolateRight:'clamp'});return <div style={{width:1050}}><div style={{fontSize:54}}>{chart.title??'Guidance range'}</div><div style={{height:22,background:'#dfe8d8',marginTop:80,position:'relative'}}><div style={{position:'absolute',left:`${20*(1-x)}%`,right:`${20*(1-x)}%`,height:22,background:color}}/><div style={{position:'absolute',left:'50%',top:-55,fontSize:40,fontWeight:800}}>{chart.midpoint??''}</div></div><div style={{display:'flex',justifyContent:'space-between',fontSize:32,marginTop:30}}><span>{chart.low??''}</span><span>{chart.high??''}</span></div></div>};

/** Movable price line with template-bound call, strike, and kick-in levels. */
const PriceLine:React.FC<{chart:any;color:string}>=({chart,color})=>{const f=useCurrentFrame();const values=(chart.values??[]).map(Number);const max=Math.max(...values,1),min=Math.min(...values,0),span=Math.max(1,max-min);const points=values.map((v:number,i:number)=>`${i*900/Math.max(1,values.length-1)},${360-(v-min)*320/span}`);const reveal=interpolate(f,[0,60],[0,1],{extrapolateRight:'clamp'});return <svg width="1000" height="480" viewBox="0 0 1000 480"><polyline points={points.join(' ')} fill="none" stroke={color} strokeWidth="12" pathLength="1" strokeDasharray="1" strokeDashoffset={1-reveal}/>{(chart.key_levels??[]).map((level:any,i:number)=>{const y=360-(Number(level.value)-min)*320/span;return <g key={i}><line x1="0" x2="920" y1={y} y2={y} stroke="#ffb703" strokeWidth="4" strokeDasharray="12 10"/><text x="930" y={y+10} fill="currentColor" fontSize="28">{level.kind}: {level.value}</text></g>})}</svg>};

/** Labeled line chart for growth comparisons and ordered time series. */
const LineChart:React.FC<{chart:any;color:string}>=({chart,color})=>{const f=useCurrentFrame();const values=(chart.values??[]).map(Number);const max=Math.max(...values,1),min=Math.min(...values,0),span=Math.max(1,max-min);const points=values.map((v:number,i:number)=>({x:70+i*860/Math.max(1,values.length-1),y:350-(v-min)*280/span,value:v}));const reveal=interpolate(f,[0,50],[0,1],{extrapolateRight:'clamp'});return <svg width="1000" height="480" viewBox="0 0 1000 480"><polyline points={points.map((p:any)=>`${p.x},${p.y}`).join(' ')} fill="none" stroke={color} strokeWidth="10" pathLength="1" strokeDasharray="1" strokeDashoffset={1-reveal}/>{points.map((p:any,i:number)=><g key={i} opacity={interpolate(f-i*6,[8,22],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp'})}><circle cx={p.x} cy={p.y} r="11" fill={color}/><text x={p.x} y={p.y-24} textAnchor="middle" fill="currentColor" fontSize="28" fontWeight="700">{chart.formatted_values?.[i]??p.value}</text><text x={p.x} y="410" textAnchor="middle" fill="currentColor" fontSize="25">{chart.labels?.[i]??''}</text></g>)}</svg>};

/** Additive bridge for cash-flow and profit reconciliations. */
const Waterfall:React.FC<{chart:any;color:string}>=({chart,color})=>{const f=useCurrentFrame();const values=(chart.values??[]).map(Number);let running=0;const totals=values.map((value:number)=>{const start=running;running+=value;return {start,end:running,value}});const extent=Math.max(1,...totals.flatMap((x:any)=>[Math.abs(x.start),Math.abs(x.end)]));return <div style={{display:'flex',alignItems:'center',gap:24,height:430}}>{totals.map((item:any,index:number)=>{const bottom=Math.min(item.start,item.end)/extent*300+70;const height=Math.abs(item.value)/extent*300;return <div key={index} style={{width:160,textAlign:'center',alignSelf:'stretch',position:'relative'}}><div style={{position:'absolute',left:10,right:10,bottom,height:interpolate(f-index*6,[0,32],[0,height],{extrapolateRight:'clamp'}),background:item.value>=0?color:'#d1495b',borderRadius:10}}/><b style={{position:'absolute',bottom:10,left:0,right:0}}>{chart.labels?.[index]??''}</b></div>})}</div>};

/** Single percentage KPI with an animated radial gauge. */
const Gauge:React.FC<{chart:any;color:string}>=({chart,color})=>{const f=useCurrentFrame();const value=Math.max(0,Math.min(100,Number(chart.values?.[0]??0)));const progress=interpolate(f,[0,45],[0,value],{extrapolateRight:'clamp'});return <div style={{width:390,height:390,borderRadius:'50%',background:`conic-gradient(${color} ${progress}%,#dce5d7 0)`,display:'grid',placeItems:'center'}}><div style={{width:260,height:260,borderRadius:'50%',background:'white',color:'#122012',display:'grid',placeItems:'center',textAlign:'center'}}><div><b style={{fontSize:66}}>{chart.formatted_values?.[0]??`${progress.toFixed(1)}%`}</b><div style={{fontSize:28,marginTop:12}}>{chart.labels?.[0]??''}</div></div></div></div>};

/** KPI and guidance cards keep the financial values dominant and readable. */
const MetricCards:React.FC<{chart:any;color:string}>=({chart,color})=>{const f=useCurrentFrame();return <div style={{display:'flex',gap:34,justifyContent:'center',flexWrap:'wrap'}}>{(chart.values??[]).map((value:number,index:number)=>{const scale=spring({frame:f-index*7,fps:30,config:{damping:16}});const formatted=chart.formatted_values?.[index];return <div key={index} style={{width:300,minHeight:210,padding:34,borderRadius:24,background:'white',color:'#122012',boxShadow:'0 18px 50px rgba(0,0,0,.16)',transform:`scale(${scale})`,borderTop:`10px solid ${color}`}}><div style={{fontSize:28,opacity:.68}}>{chart.labels?.[index]??'KPI'}</div><div style={{fontSize:52,fontWeight:900,marginTop:28}}>{formatted??Number(value).toLocaleString()}</div>{!formatted&&<div style={{fontSize:23,opacity:.65}}>{chart.units?.[index]??chart.unit??''}</div>}</div>})}</div>};

/** Compact table for mixed-unit values and straightforward data listings. */
const DataTable:React.FC<{chart:any;color:string}>=({chart,color})=><div style={{width:1050,background:'white',color:'#122012',borderRadius:24,overflow:'hidden',boxShadow:'0 18px 50px rgba(0,0,0,.14)'}}>{(chart.values??[]).map((value:number,index:number)=><div key={index} style={{display:'grid',gridTemplateColumns:'1fr auto',gap:40,alignItems:'center',padding:'25px 38px',borderBottom:index+1<(chart.values?.length??0)?'1px solid #dce5d7':'none'}}><span style={{fontSize:31}}>{chart.labels?.[index]??''}</span><b style={{fontSize:38,color}}>{chart.formatted_values?.[index]??`${Number(value).toLocaleString()} ${chart.units?.[index]??chart.unit??''}`}</b></div>)}</div>;

/** Select one of the finite renderer templates; schema validation rejects unknown types. */
const Chart:React.FC<{chart:any;color:string}>=({chart,color})=>chart.type==='bar'?<Bars chart={chart} color={color}/>:chart.type==='horizontal_bar'?<HorizontalBars chart={chart} color={color}/>:chart.type==='donut'?<Donut chart={chart} color={color}/>:chart.type==='range'?<Guidance chart={chart} color={color}/>:chart.type==='line'?<LineChart chart={chart} color={color}/>:chart.type==='waterfall'?<Waterfall chart={chart} color={color}/>:chart.type==='gauge'?<Gauge chart={chart} color={color}/>:chart.type==='metric_cards'?<MetricCards chart={chart} color={color}/>:chart.type==='table'?<DataTable chart={chart} color={color}/>:<PriceLine chart={chart} color={color}/>;

/** Show only the short subtitle cue active at the current global audio frame. */
const Caption:React.FC<{cues:CaptionCue[];sceneFrom:number;config?:CaptionConfig}>=({cues,sceneFrom,config})=>{const local=useCurrentFrame();const {height}=useVideoConfig();const cue=cues.find(item=>sceneFrom+local>=item.from_frame&&sceneFrom+local<=item.to_frame);if(config?.enabled===false||!cue)return null;const safe=config?.safe_zone;const maxLines=config?.max_lines??2;return <div style={{position:'absolute',left:safe?.left??96,right:safe?undefined:96,width:safe?Math.max(100,safe.right-safe.left):undefined,bottom:Math.max(36,height-(safe?.bottom??height-60)),overflow:'hidden',background:'rgba(0,0,0,.82)',color:'white',borderRadius:16,padding:'14px 28px',fontSize:36,lineHeight:1.35,textAlign:'center',boxSizing:'border-box',display:'-webkit-box',WebkitBoxOrient:'vertical',WebkitLineClamp:maxLines}}>{cue.text}</div>};

/** Apply only the renderer-supported transition selected in the scene plan. */
const transitionStyle=(template:SceneSpec['transition'],progress:number):React.CSSProperties=>template==='fade'?{opacity:progress}:template==='slide'?{transform:`translateX(${(1-progress)*120}px)`,opacity:progress}:template==='wipe'?{clipPath:`inset(0 ${100*(1-progress)}% 0 0)`}:template==='zoom'?{transform:`scale(${.88+.12*progress})`,opacity:progress}:{opacity:1};

/** Render one scene while keeping chart/media content above the caption region. */
const Scene:React.FC<{scene:SceneSpec;index:number;manifest:Manifest;chart:any;asset:any;event:any}>=({scene,index,manifest,chart,asset,event})=>{const f=useCurrentFrame();const {fps}=useVideoConfig();const enter=scene.transition==='cut'?1:spring({frame:f,fps,config:{damping:20}});const color=manifest.brand?.primary_color??'#76B900';const ink='#0d160d';const isDisclaimer=scene.kind?scene.kind==='disclaimer':/disclaimer|免责声明|法律提示/i.test(`${scene.purpose} ${scene.title??''}`);const success=asset?.attempts?.find((x:any)=>x.status==='succeeded'&&x.result);const mediaUrl=success?.result?.video_url??success?.result?.image_urls?.[0]??success?.result?.url??success?.result?.artifact_url;const isVideo=asset?.strategy==='bach_text_to_video'||asset?.strategy==='bach_elements_to_video';const mediaDurationFrames=Math.max(1,Math.round(Math.max(6,Math.min(10,scene.duration_seconds))*fps));const media=scene.visual_kind==='broll'&&mediaUrl?(isVideo?<Loop durationInFrames={mediaDurationFrames}><OffthreadVideo src={mediaUrl} muted style={{width:'100%',height:'100%',objectFit:'cover'}}/></Loop>:<Img src={mediaUrl} style={{width:'80%',height:'80%',objectFit:'contain',transform:`scale(${1+.06*enter})`}}/>):null;const cues=(manifest.caption_cues??manifest.timeline.caption_cues??[]).filter(c=>c.scene_id===scene.id);return <AbsoluteFill style={{background:index%2?'#f3f7ef':'#111b10',color:index%2?ink:'white',fontFamily:`${manifest.brand?.font_family??'Inter'}, PingFang SC, sans-serif`,padding:'55px 90px 165px',...transitionStyle(scene.transition,enter)}}><div style={{fontSize:30,color,fontWeight:800}}>FINANCIAL VIDEO</div><h1 style={{fontSize:70,maxWidth:1500,margin:'24px 0'}}>{scene.title??scene.purpose}</h1><div style={{flex:1,display:'grid',placeItems:'center',minHeight:0}}>{isDisclaimer?<div style={{fontSize:42,lineHeight:1.6,textAlign:'center',maxWidth:1400}}>{manifest.disclaimer}</div>:chart?<Chart chart={chart} color={color}/>:media??<div style={{fontSize:220}}>📊✨</div>}</div><Caption cues={cues} sceneFrom={event.from_frame} config={manifest.captions}/></AbsoluteFill>};

/** Map approved manifest scenes to deterministic frame ranges and templates. */
export const FinancialVideo:React.FC<Manifest>=(props)=><AbsoluteFill>{props.audio?.src?<Audio src={staticFile(props.audio.src)}/>:null}{props.scenes.map((scene,index)=>{const event=props.timeline.events.find((item:any)=>item.scene_id===scene.id);if(!event)return null;const chart=props.charts.charts.find((x:any)=>x.id===scene.chart);const asset=props.assets?.scenes.find((x:any)=>x.scene_id===scene.id);return <Sequence key={scene.id} from={event.from_frame} durationInFrames={event.to_frame-event.from_frame+1}><Scene scene={scene} index={index} manifest={props} chart={chart} asset={asset} event={event}/></Sequence>})}</AbsoluteFill>;
